# Generated by Django 5.2.10 on 2026-01-16 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_clean', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('total_episode', models.CharField(blank=True, max_length=50)),
                ('anime_type', models.CharField(blank=True, max_length=30)),
                ('year_release', models.CharField(blank=True, max_length=10)),
                ('content_rating', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('total_rating', models.FloatField(default=0.0)),
                ('cover', models.CharField(blank=True, max_length=255)),
                ('wallpaper', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnimeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
